inherit_from:
  - .disabled.yml
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'client/**/*'
    - 'db/**/*'
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30
